server:
  port: 8888

spring:
  application:
    name: config-server

  security:
    user:
      name: config
      password: password

  cloud:
    config:
      server:
        git:
          uri: file:///${user.home}/projects/helsana/spring-cloud-config-client-bootstrap/eureka-first-bootstrap-config

eureka:
  instance:
    metadata-map:
      # DiscoveryClientConfigServiceBootstrapConfiguration#refresh
      user: ${spring.security.user.name}
      password: ${spring.security.user.password}

  client:
    service-url:
      defaultZone: http://eureka:eureka-dev@localhost:8761/eureka/

management:
  endpoints:
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: ALWAYS

